name: journal_ai_mobile
description: Android Flutter client for Journal AI
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

